---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "a dashboard"
subtitle: ""
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Demo !"
  icon: "fa fa-grin"
  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 
  - name: "Edit this dashboard"
    icon: "fas fa-brands fa-github"
    url: "https://github.com/europeanpirates/dashboard"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Social"
    icon: "fas fa-face-meh"
    items:
      - name: "YouTube"
        icon: "fas fa-brands fa-youtube"
        url: "https://www.youtube.com/channel/UC0St6SkXApFki6dc1Q1BVKA"
      - name: "Facebook"
        icon: "fas fa-brands fa-facebook"
        url: "https://www.facebook.com/europeanpirateparty/"
      - name: "Twitter/X"
        icon: "fas fa-brands fa-twitter"
        url: "https://twitter.com/EuropeanPirates"
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Wiki"
        icon: "fas fa-paragraph"
        url: "https://wiki.ppeu.net"
      - name: "mattermost"
        icon: "fas fa-comments"
        url: "https://mattermost.european-pirateparty.eu"
      - name: "Mailing lists"
        icon: "fas fa-envelope-open"
        url: "https://lists.european-pirateparty.eu/sympa"
      - name: "Discourse"
        icon: "fas fa-brands fa-discourse"
        url: "https://discourse.european-pirateparty.eu"
  - name: "Delegation"
    icon: 
    items: 
      - name: "login"
        url: "#"
      - name: "nextcloud"
        url: "#"
      - name: "gitlab"
        url:  "#"